# Generated by Django 3.1.5 on 2021-01-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20210115_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록날짜'),
        ),
    ]
