# Generated by Django 3.1.5 on 2021-01-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soogle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '글', 'verbose_name_plural': '글'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='글',
        ),
    ]
