# Generated by Django 3.1.5 on 2021-01-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soogle', '0002_auto_20210115_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Post',
        ),
    ]
